export const translations = {
    en: {
        nav: {
            home: "HOME",
            about: "ABOUT",
            projects: "PROJECTS",
            achievements: "ACHIEVEMENTS",
            journey: "JOURNEY",
            contact: "CONTACT",
        },
        hero: {
            badges: ["FRONTEND ENGINEER", "FREELANCER"],
            tagBadges: ["INFORMATICS", "UI/UX", "GRAPHIC DESIGN"],
            openToWork: "OPEN TO WORK",
            basedIn: "BASED IN INDONESIA, ID",
            today: "TODAY:",
            scrollDown: "SCROLL DOWN",
        },
        about: {
            title: "ABOUT",
            greeting: "",
            hi: "Hi, I'm ",
            name: "Muhammad Hanif Hawari",
            bio1: "I am a Computer Science Student at University of Amikom Yogyakarta. I have the skills to build websites that are modern, interactive, and user centered. My journey in web development started from curiosity and has grown into a full-blown passion.",
            bio2: "I specialize in building modern web applications using React, Next.js, and the latest web technologies. I believe in writing clean, maintainable code and creating designs that not only look great but also provide seamless user experiences.",
            downloadResume: "Download Full CV",
            discordUser: "@hanifhawari",
            online: "Online",
            hireMe: "Hire Me",
            education: {
                title: "INFORMATICS (GPA 3.3)",
                university: "UNIVERSITAS AMIKOM YOGYAKARTA",
                description: "Built a strong foundation in software engineering, algorithms, and database architecture. Focused on practical web & mobile development skills.",
                tags: ["ALGORITHM", "DATABASE", "WEB DEVELOPMENT"],
                year: "2026",
                badge: "ACADEMIC",
            },
            techStack: {
                title: "Tech Stack",
                core: {
                    title: "Core Languages",
                    items: ["HTML5", "CSS3", "PHP", "Java", "JavaScript", "SQL"],
                },
                frameworks: {
                    title: "Frameworks & UI",
                    items: ["Laravel", "Next.js", "React", "Capacitor", "Tailwind", "Bootstrap"],
                },
                tools: {
                    title: "Tools",
                    items: ["Vite", "Git", "Notion", "GitHub", "Figma", "Postman"],
                },
            },
        },
        projects: {
            title: "SELECTED WORKS",
            subtitle: "A curated collection of projects that showcase my skills and passion for building digital experiences.",
            liveDemo: "Live Demo",
            sourceCode: "Code",
            items: [
                {
                    category: "E-COMMERCE",
                    title: "Aura Store",
                    description: "A modern e-commerce platform offering a seamless shopping experience with an elegant UI, fast performance, and responsive design. Built for scalability and user engagement.",
                    stats: [
                        { value: "100%", label: "Responsive" },
                        { value: "98%", label: "Uptime" },
                        { value: "1 sec", label: "Load Time" },
                    ],
                    tech: ["React", "TypeScript", "Tailwind CSS", "Vite", "Zustand"],
                    caseStudy: "Read Case Study",
                    liveUrl: "https://aura-store-ecommerce.vercel.app",
                    codeUrl: "https://github.com/HanifHawari/Aura-Store.git",
                    image: "/ecommerce.png",
                    caseStudyContent: {
                        overview: "This project aims to revolutionize the local online shopping experience by building a highly responsive Headless e-commerce platform. The primary focus is on page load metrics and an intuitive checkout flow to maximize customer retention.",
                        challenges: "Handling a persistent shopping cart state management cycle on the client side, while keeping the initial rendering time under 1 second on mobile devices.",
                        solutions: "Built an SPA architecture with React and Vite for instant asset delivery. Utilized Zustand for lightweight state management without boilerplate, and Tailwind CSS for a modular design system.",
                        results: "Achieved high performance metrics with load speeds under 1 second. Seamless UI interactions without page reloads successfully reduced customer bounce rates."
                    }
                },
                {
                    category: "ARTIFICIAL INTELLIGENCE",
                    title: "Fitmind AI",
                    description: "An AI-powered health and fitness application that provides intelligent recommendations. Features personalized insights and a smart assistant to guide your wellness journey.",
                    stats: [
                        { value: "Active", label: "Development" },
                        { value: "2 sec", label: "AI Response" },
                        { value: "3+", label: "AI Features" },
                    ],
                    tech: ["React Native", "Google Gemini API", "Firebase", "Tailwind"],
                    caseStudy: "Read Case Study",
                    liveUrl: "https://fitmind-ai.up.railway.app",
                    codeUrl: "https://github.com/HanifHawari/ProjectPDMLLM",
                    image: "/fitness.png",
                    caseStudyContent: {
                        overview: "Developing a next-generation virtual health assistant that not only tracks passive metrics but proactively provides context-based recommendations using Generative AI.",
                        challenges: "Keeping AI response latency low on the mobile app, and designing a data architecture capable of synchronizing user health profiles in real-time across devices.",
                        solutions: "Integrated Google Gemini API through a decentralized architecture using Firebase. Built a reactive conversational interface and smooth data transition animations using React Native.",
                        results: "The app delivers highly personalized health insights and workout advice with response latencies under 2 seconds, creating a truly realistic AI personal trainer experience."
                    }
                },
                {
                    category: "LANDING PAGE",
                    title: "Kopi Josjis",
                    description: "A visually appealing website for a local coffee shop. Features a dynamic menu display, responsive design, and an elegant aesthetic to attract coffee enthusiasts.",
                    stats: [
                        { value: "10+", label: "Menu Items" },
                        { value: "100%", label: "Responsive" },
                        { value: "1 sec", label: "Load Time" },
                    ],
                    tech: ["HTML5", "CSS3", "JavaScript", "PHP", "MySQL"],
                    caseStudy: "Read Case Study",
                    liveUrl: "https://kopijosjis.vercel.app",
                    codeUrl: "https://github.com/HanifHawari/coffeeshop",
                    image: "/cms.png",
                    caseStudyContent: {
                        overview: "Digitalizing the Kopi Josjis brand identity through a custom web platform. The goal is to create an interactive digital representation while facilitating dynamic daily menu updates by shop staff.",
                        challenges: "The client required an extremely simple content management backend (CMS) with no steep learning curve, yet the frontend performance had to match modern web standards.",
                        solutions: "Designed a lightweight backend architecture with PHP and MySQL for a custom CMS. The frontend was built with a mobile-first approach using Vanilla JavaScript and pure CSS to minimize payload size.",
                        results: "The website achieved maximum performance scores. The highly intuitive admin panel now allows staff to update menu availability and pricing in seconds without technical assistance."
                    }
                },
            ],
        },
        achievements: {
            title: "MY ACHIEVEMENTS",
            subtitle: "An achievement that is rarely achieved by other people and this is the proudest award for me.",
            liveDemo: "Kunjungi",
            items: [
                {
                    category: "ALL PRESTASI",
                    title: "MOBILE LEGENDS",
                    description: "Successfully reached the Immortal rank in Mobile Legends with a total of 324 matches and a 65.74% win rate in Season 40.",
                    stats: [
                        { value: "35", label: "WIN STREAK" },
                        { value: "52.76%", label: "WR ALL SEASON" },
                        { value: "594", label: "ALL SKIN" },
                    ],
                    archiveLabel: "PHOTO ARCHIVE",
                    archiveTap: "Click to open folder",
                    detail: "View Details",
                    liveUrl: "https://www.mobilelegends.com",
                    image: "/pencapaian.png",
                    galleryImages: [
                        { src: "/rank-immortal.png", caption: "Rank Immortal" },
                    ],
                },
            ],
        },
        journey: {
            title: "MY JOURNEY",
            subtitle: "A timeline of my professional and academic milestones.",
            items: [
                {
                    year: "2026",
                    badge: "PROFESSIONAL",
                    role: "FULL-STACK DEVELOPER",
                    company: "Tech Company",
                    description: "Working on cutting-edge web applications using modern technologies. Contributing to the development of scalable and performant solutions for clients across various industries.",
                    tags: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
                    archiveLabel: "PROJECT ARCHIVE",
                    archiveTap: "Tap to Open",
                    projects: [
                        { name: "Portfolio GitHub", status: "Public Repository", url: "https://github.com/HanifHawari/portofolio" }
                    ],
                },
                {
                    year: "2026",
                    badge: "FREELANCE",
                    role: "FREELANCE DEVELOPER",
                    company: "Self-Employed",
                    description: "Took on freelance projects building custom websites and web applications for small businesses and startups. Focused on delivering high-quality, responsive designs.",
                    tags: ["React", "Node.js", "Figma"],
                    archiveLabel: "PROJECT ARCHIVE",
                    archiveTap: "Tap to Open",
                },
                {
                    year: "2026",
                    badge: "INTERNSHIP",
                    role: "WEB DEVELOPMENT INTERN",
                    company: "Digital Agency",
                    description: "Gained hands-on experience in full-stack web development. Collaborated with senior developers on client projects and learned agile development methodologies.",
                    tags: ["Laravel", "PHP", "MySQL", "Bootstrap"],
                    archiveLabel: "PROJECT ARCHIVE",
                    archiveTap: "Tap to Open",
                },
                {
                    year: "2024",
                    badge: "ACADEMIC",
                    role: "STUDENT DEVELOPER",
                    company: "Amikom University Yogyakarta",
                    description: "Focused on academic projects and personal development. Built several web applications as part of coursework and participated in coding competitions.",
                    tags: ["Java", "Python", "HTML/CSS", "Git"],
                    archiveLabel: "PROJECT ARCHIVE",
                    archiveTap: "Tap to Open",
                },
                {
                    year: "2024",
                    badge: "ACADEMIC",
                    role: "S1 INFORMATICS",
                    company: "Amikom University Yogyakarta",
                    description: "Started my journey in Information Systems. Built a strong foundation in software engineering, business logic, and database structure.",
                    tags: ["Algorithm", "Database", "Problem Solving"],
                    archiveLabel: "PROJECT ARCHIVE",
                    archiveTap: "Tap to Open",
                },
            ],
        },
        geistVillage: {
            title: "The Geist Village",
            subtitle: "An interactive physics playground. Click and drag the objects!",
            loading: "Loading Playground...",
            preparing: "Preparing Physics Engine...",
            reset: "Reset",
            words: [
                "Next.js", "React", "TypeScript", "Tailwind", "Figma",
                "Node.js", "Git", "Laravel", "CSS3", "HTML5",
                "JavaScript", "PostgreSQL", "Docker", "Vercel", "Design",
                "Code", "Build", "Ship", "Create", "Debug",
            ],
        },
        contact: {
            title: "Let's Collaborate",
            subtitle: "Have a project in mind? Let's work together to create something amazing.",
            directEmail: "Direct Email",
            email: "muhanwar.ipuh@gmail.com",
            socialLinks: "Social Links",
            form: {
                name: "Name",
                namePlaceholder: "Your full name",
                email: "Email",
                emailPlaceholder: "your@email.com",
                subject: "Subject",
                subjects: ["Project Collaboration", "Job Opportunity", "General Inquiry"],
                message: "Message",
                messagePlaceholder: "Tell me about your project...",
                send: "SEND MESSAGE",
                sending: "SENDING...",
                success: "Message sent successfully!",
                error: "Failed to send message. Please try again.",
            },
        },
        footer: {
            copyright: `©${new Date().getFullYear()} Muhammad Hanif Hawari. All Rights Reserved`,
            location: "Indonesia",
            remote: "Available for Remote Work",
        },
    },
    id: {
        nav: {
            home: "BERANDA",
            about: "TENTANG",
            projects: "PROYEK",
            achievements: "PENCAPAIAN",
            journey: "PERJALANAN",
            contact: "KONTAK",
        },
        hero: {
            badges: ["FRONTEND ENGINEER", "FREELANCER"],
            tagBadges: ["INFORMATICS", "UI/UX", "GRAPHIC DESIGN"],
            openToWork: "TERBUKA UNTUK BEKERJA",
            basedIn: "BERBASIS DI INDONESIA, ID",
            today: "HARI INI:",
            scrollDown: "GULIR KEBAWAH",
        },
        about: {
            title: "TENTANG SAYA",
            greeting: "",
            hi: "Hai, Saya ",
            name: "Muhammad Hanif Hawari",
            bio1: "Saya adalah Mahasiswa Informatika yang sedang berkuliah di Universitas Amikom Yogyakarta. Saya memiliki skill dalam membuat website yang modern, interaktif, dan berpusat pada pengguna. Perjalanan saya dalam pengembangan web dimulai dari rasa ingin tahu dan telah berkembang menjadi sebuah passion.",
            bio2: "Saya mengkhususkan diri dalam membangun aplikasi web modern menggunakan React, Next.js, dan teknologi web terbaru. Saya percaya pada penulisan kode yang bersih dan mudah dipelihara serta membuat desain yang tidak hanya terlihat bagus tetapi juga memberikan pengalaman pengguna yang mulus.",
            downloadResume: "Unduh CV Lengkap",
            discordUser: "@hanifhawari",
            online: "Online",
            hireMe: "Rekrut Saya",
            education: {
                title: "INFORMATIKA (IPK 3.3)",
                university: "UNIVERSITAS AMIKOM YOGYAKARTA",
                description: "Membangun fondasi yang kuat dalam rekayasa perangkat lunak, algoritma, dan arsitektur database. Fokus pada pengembangan web & mobile yang praktis.",
                tags: ["ALGORITMA", "DATABASE", "PENGEMBANGAN WEB"],
                year: "2026",
                badge: "AKADEMIK",
            },
            techStack: {
                title: "Tech Stack",
                core: {
                    title: "Bahasa Inti",
                    items: ["HTML5", "CSS3", "PHP", "Java", "JavaScript", "SQL"],
                },
                frameworks: {
                    title: "Framework & UI",
                    items: ["Laravel", "Next.js", "React", "Capacitor", "Tailwind", "Bootstrap"],
                },
                tools: {
                    title: "Alat",
                    items: ["Vite", "Git", "Notion", "GitHub", "Figma", "Postman"],
                },
            },
        },
        projects: {
            title: "KARYA TERPILIH",
            subtitle: "Koleksi proyek yang menampilkan keterampilan dan passion saya dalam membangun pengalaman digital.",
            liveDemo: "Live Demo",
            sourceCode: "Code",
            items: [
                {
                    category: "E-COMMERCE",
                    title: "Aura Store",
                    description: "Platform e-commerce modern yang menawarkan pengalaman berbelanja mulus dengan UI elegan, performa cepat, dan desain responsif. Dibangun untuk skalabilitas dan interaksi pengguna.",
                    stats: [
                        { value: "100%", label: "Responsif" },
                        { value: "98%", label: "Uptime" },
                        { value: "1 dtk", label: "Waktu Muat" },
                    ],
                    tech: ["React", "TypeScript", "Tailwind CSS", "Vite", "Zustand"],
                    caseStudy: "Baca Studi Kasus",
                    liveUrl: "https://aura-store-ecommerce.vercel.app",
                    codeUrl: "https://github.com/HanifHawari/Aura-Store",
                    image: "/ecommerce.png",
                    caseStudyContent: {
                        overview: "Proyek ini bertujuan merevolusi pengalaman belanja online lokal dengan membangun platform e-commerce Headless. Fokus utama adalah pada metrik kecepatan muat halaman dan alur checkout yang sangat intuitif untuk memaksimalkan retensi pelanggan.",
                        challenges: "Menangani siklus manajemen state keranjang belanja yang persisten di sisi klien, sekaligus menekan waktu rendering awal agar di bawah 1 detik pada perangkat seluler.",
                        solutions: "Membangun arsitektur SPA dengan React dan sistem build Vite untuk pengiriman aset instan. Menggunakan Zustand untuk state management ringan tanpa boilerplate, serta Tailwind CSS untuk sistem desain modular.",
                        results: "Mencapai metrik performa tinggi dengan kecepatan muat di bawah 1 detik. Interaksi UI yang mulus tanpa reload halaman berhasil memangkas rasio pantulan (bounce rate) pelanggan."
                    }
                },
                {
                    category: "KECERDASAN BUATAN",
                    title: "Fitmind AI",
                    description: "Aplikasi kesehatan dan kebugaran bertenaga AI yang menyediakan rekomendasi cerdas. Dilengkapi wawasan yang dipersonalisasi dan asisten pintar untuk memandu perjalanan kesehatan Anda.",
                    stats: [
                        { value: "Aktif", label: "Pengembangan" },
                        { value: "2 dtk", label: "Respons AI" },
                        { value: "3+", label: "Fitur AI" },
                    ],
                    tech: ["React Native", "Google Gemini API", "Firebase", "Tailwind"],
                    caseStudy: "Baca Studi Kasus",
                    liveUrl: "https://fitmind-ai.up.railway.app",
                    codeUrl: "https://github.com/HanifHawari/ProjectPDMLLM",
                    image: "/fitness.png",
                    caseStudyContent: {
                        overview: "Mengembangkan asisten kesehatan virtual generasi berikutnya yang tidak hanya melacak metrik pasif, tetapi secara proaktif memberikan rekomendasi berbasis konteks menggunakan AI Generatif.",
                        challenges: "Menjaga latensi respons AI tetap rendah di aplikasi mobile, serta merancang arsitektur data yang mampu menyinkronkan profil kesehatan pengguna secara real-time antar perangkat.",
                        solutions: "Mengintegrasikan Google Gemini API melalui arsitektur terdesentralisasi menggunakan Firebase. Membangun antarmuka percakapan reaktif dan animasi transisi data yang smooth menggunakan React Native.",
                        results: "Aplikasi mampu memberikan insight kesehatan dan saran latihan sangat personal dengan latensi respons di bawah 2 detik, menciptakan pengalaman pelatih pribadi AI yang terasa nyata."
                    }
                },
                {
                    category: "HALAMAN LANDAS",
                    title: "Kopi Josjis",
                    description: "Situs web yang menarik secara visual untuk kedai kopi lokal. Menampilkan menu dinamis, desain responsif, dan estetika elegan untuk menarik pecinta kopi.",
                    stats: [
                        { value: "10+", label: "Item Menu" },
                        { value: "100%", label: "Responsif" },
                        { value: "1 dtk", label: "Waktu Muat" },
                    ],
                    tech: ["HTML5", "CSS3", "JavaScript", "PHP", "MySQL"],
                    caseStudy: "Baca Studi Kasus",
                    liveUrl: "https://kopijosjis.vercel.app",
                    codeUrl: "https://github.com/HanifHawari/coffeeshop",
                    image: "/cms.png",
                    caseStudyContent: {
                        overview: "Digitalisasi identitas merek Kopi Josjis melalui platform web kustom. Tujuannya adalah menciptakan representasi digital interaktif sekaligus memfasilitasi pembaruan menu harian secara dinamis oleh staf kedai.",
                        challenges: "Klien membutuhkan sistem backend manajemen konten (CMS) yang sangat sederhana tanpa kurva belajar yang curam, namun performa frontend harus tetap setara dengan standar web modern.",
                        solutions: "Merancang arsitektur backend ringan dengan PHP dan MySQL untuk CMS kustom. Frontend dibangun dengan pendekatan mobile-first menggunakan Vanilla JavaScript dan CSS murni untuk meminimalkan ukuran payload.",
                        results: "Situs web mencapai skor performa maksimal. Panel admin yang sangat intuitif kini memungkinkan staf memperbarui ketersediaan menu dan harga dalam hitungan detik tanpa bantuan teknis."
                    }
                },
            ],
        },
        achievements: {
            title: "PENCAPAIAN SAYA",
            subtitle: "Suatu pencapaian yang jarang di dapati oleh orang lain dan ini menjadi penghargaan yang paling membanggakan bagi saya.",
            liveDemo: "Kunjungi",
            items: [
                {
                    category: "ALL PRESTASI",
                    title: "MOBILE LEGENDS",
                    description: "Berhasil mencapai rank Immortal di Mobile Legends dengan total 324 match dan win rate 65.74% pada season 40.",
                    stats: [
                        { value: "35", label: "WIN STREAK" },
                        { value: "52.76%", label: "WR ALL SEASON" },
                        { value: "594", label: "TOTAL SKIN" },
                    ],
                    archiveLabel: "ARSIP FOTO",
                    archiveTap: "Ketuk untuk buka folder",
                    detail: "Lihat Detail",
                    liveUrl: "https://www.mobilelegends.com",
                    image: "/pencapaian.png",
                    galleryImages: [
                        { src: "/rank-immortal.png", caption: "Rank Immortal" },
                    ],
                },
            ],
        },
        journey: {
            title: "PERJALANAN SAYA",
            subtitle: "Garis waktu pencapaian profesional dan akademis saya.",
            items: [
                {
                    year: "2026",
                    badge: "PROFESSIONAL",
                    role: "FULL-STACK DEVELOPER",
                    company: "Perusahaan Teknologi",
                    description: "Bekerja pada aplikasi web mutakhir menggunakan teknologi modern. Berkontribusi pada pengembangan solusi yang skalabel dan performan untuk klien di berbagai industri.",
                    tags: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
                    archiveLabel: "ARSIP PROYEK",
                    archiveTap: "Ketuk untuk Buka",
                    projects: [
                        { name: "Portfolio GitHub", status: "Repositori Publik", url: "https://github.com/HanifHawari/portofolio" }
                    ],
                },
                {
                    year: "2026",
                    badge: "FREELANCE",
                    role: "FREELANCE DEVELOPER",
                    company: "Wiraswasta",
                    description: "Mengerjakan proyek freelance membangun situs web dan aplikasi web kustom untuk bisnis kecil dan startup. Fokus pada pengiriman desain responsif berkualitas tinggi.",
                    tags: ["React", "Node.js", "Figma"],
                    archiveLabel: "ARSIP PROYEK",
                    archiveTap: "Ketuk untuk Buka",
                },
                {
                    year: "2026",
                    badge: "MAGANG",
                    role: "MAGANG PENGEMBANGAN WEB",
                    company: "Agensi Digital",
                    description: "Memperoleh pengalaman langsung dalam pengembangan web full-stack. Berkolaborasi dengan pengembang senior pada proyek klien dan mempelajari metodologi pengembangan agile.",
                    tags: ["Laravel", "PHP", "MySQL", "Bootstrap"],
                    archiveLabel: "ARSIP PROYEK",
                    archiveTap: "Ketuk untuk Buka",
                },
                {
                    year: "2024",
                    badge: "AKADEMIK",
                    role: "MAHASISWA INFORMATIKA",
                    company: "Universitas Amikom Yogyakarta",
                    description: "Fokus pada proyek akademik dan pengembangan diri. Membangun beberapa aplikasi web sebagai bagian dari tugas kuliah dan berpartisipasi dalam kompetisi coding.",
                    tags: ["Java", "Python", "HTML/CSS", "Git"],
                    archiveLabel: "ARSIP PROYEK",
                    archiveTap: "Ketuk untuk Buka",
                },
                {
                    year: "2024",
                    badge: "AKADEMIK",
                    role: "S1 INFORMATIKA",
                    company: "Universitas Amikom Yogyakarta",
                    description: "Memulai perjalanan di Informatika. Membangun fondasi yang kuat dalam rekayasa perangkat lunak, logika bisnis, dan struktur basis data.",
                    tags: ["Algoritma", "Database", "Problem Solving"],
                    archiveLabel: "ARSIP PROYEK",
                    archiveTap: "Ketuk untuk Buka",
                },
            ],
        },
        geistVillage: {
            title: "The Geist Village",
            subtitle: "Taman bermain fisika interaktif. Klik dan seret objeknya!",
            loading: "Memuat Taman Bermain...",
            preparing: "Menyiapkan Mesin Fisika...",
            reset: "Reset",
            words: [
                "Next.js", "React", "TypeScript", "Tailwind", "Figma",
                "Node.js", "Git", "Laravel", "CSS3", "HTML5",
                "JavaScript", "PostgreSQL", "Docker", "Vercel", "Design",
                "Kode", "Bangun", "Kirim", "Buat", "Debug",
            ],
        },
        contact: {
            title: "Ayo Kerja Sama",
            subtitle: "Punya proyek dalam pikiran? Mari bekerja sama untuk membuat sesuatu yang luar biasa.",
            directEmail: "Email Langsung",
            email: "muhanwar.ipuh@gmail.com",
            socialLinks: "Tautan Sosial",
            form: {
                name: "Nama",
                namePlaceholder: "Nama lengkap",
                email: "Email",
                emailPlaceholder: "email@.com",
                subject: "Subjek",
                subjects: ["Kolaborasi Proyek", "Kesempatan Kerja", "Pertanyaan Umum"],
                message: "Pesan",
                messagePlaceholder: "Ceritakan tentang proyek ...",
                send: "KIRIM PESAN",
                sending: "MENGIRIM...",
                success: "Pesan berhasil dikirim!",
                error: "Gagal mengirim pesan. Silakan coba lagi.",
            },
        },
        footer: {
            copyright: `©${new Date().getFullYear()} Muhammad Hanif Hawari. Hak Cipta Dilindungi`,
            location: "Indonesia",
            remote: "Tersedia untuk Kerja Remote",
        },
    },
};
